apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticket-prod

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: user-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: event-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2