apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: ticket-dev
  labels:
    app: notification-service   # 👈 추가
spec:
  selector:
    app: notification-service
  ports:
    - name: http               # 👈 추가 (핵심🔥)
      protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP