apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ticket-dev
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP